package com.iven.musicplayergo.models

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class PlaylistMusic(
    @PrimaryKey(autoGenerate = true)
    val autoGeneratedId: Long?,
    val playlistName: String,
    val song: Pair<Music, Int>
)
